name: Technical Discussion
description: You want to discuss technical aspects of changes you intend to make
labels:
  - enhancement
body:
    - type: textarea
      id: changes
      validations:
        required: true
      attributes:
        label: Changes
        description: Explain the change and the motivations behind it.
        placeholder: |
          For example, if you plan to rely on a new dependency, explain why and what it brings to the project.

          If you plan to make significant changes, go roughly over the steps you intend to take and how you would divide the change in PRs of a manageable size.
