name: Scheduled tasks 🕑

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:
permissions:
  issues: write
  pull-requests: write

jobs:
  issues:
    name: Check issues
    runs-on: ubuntu-latest
    if: ${{ contains(github.repository, 'jellyfin/') }}
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.JF_BOT_TOKEN }}
          operations-per-run: 75
          days-before-stale: 120
          days-before-pr-stale: -1
          days-before-close: 21
          days-before-pr-close: -1
          exempt-issue-labels: regression,security,roadmap,future,feature,enhancement,confirmed
          stale-issue-label: stale
          stale-issue-message: |-
            This issue has gone 120 days without comment. To avoid abandoned issues, it will be closed in 21 days if there are no new comments.

            If you're the original submitter of this issue, please comment confirming if this issue still affects you in the latest release or master branch, or close the issue if it has been fixed. If you're another user also affected by this bug, please comment confirming so. Either action will remove the stale label.

            This bot exists to prevent issues from becoming stale and forgotten. Jellyfin is always moving forward, and bugs are often fixed as side effects of other changes. We therefore ask that bug report authors remain vigilant about their issues to ensure they are closed if fixed, or re-confirmed - perhaps with fresh logs or reproduction examples - regularly. If you have any questions you can reach us on [Matrix or Social Media](https://jellyfin.org/contact).

  prs-conflicts:
    name: Check PRs with merge conflicts
    runs-on: ubuntu-latest
    if: ${{ contains(github.repository, 'jellyfin/') }}
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e # v9.0.0
        with:
          repo-token: ${{ secrets.JF_BOT_TOKEN }}
          operations-per-run: 75
          # The merge conflict action will remove the label when updated
          remove-stale-when-updated: false
          days-before-stale: -1
          days-before-close: 90
          days-before-issue-close: -1
          stale-pr-label: merge conflict
          close-pr-message: |-
            This PR has been closed due to having unresolved merge conflicts.

  update:
    name: Update the Jellyfin SDK
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'jellyfin/jellyfin-web' }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          ref: master
          token: ${{ secrets.JF_BOT_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Install latest unstable SDK
        run: |
          npm i --save @jellyfin/sdk@unstable
          VERSION=$(jq -r '.dependencies["@jellyfin/sdk"]' package.json)
          echo "JF_SDK_VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Open a pull request
        uses: peter-evans/create-pull-request@8867c4aba1b742c39f8d0ba35429c2dfa4b6cb20 # v7.0.1
        with:
          token: ${{ secrets.JF_BOT_TOKEN }}
          commit-message: Update @jellyfin/sdk to ${{env.JF_SDK_VERSION}}
          committer: jellyfin-bot <team@jellyfin.org>
          author: jellyfin-bot <team@jellyfin.org>
          branch: update-jf-sdk
          delete-branch: true
          title: Update @jellyfin/sdk to ${{env.JF_SDK_VERSION}}
          body: |
            **Changes**
            Updates to the latest unstable @jellyfin/sdk build
          labels: |
            dependencies
            npm
